{
 "title": "Student Task Manager",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(flask_app_request_count_total)"
    }
   ]
  },
  {
   "title": "Requests per Endpoint (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(flask_app_request_count_total[5m])) by (endpoint)"
    }
   ]
  },
  {
   "title": "Average Request Latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_app_request_latency_seconds_sum[5m]) / rate(flask_app_request_latency_seconds_count[5m])"
    }
   ]
  }
 ]
}